### ISSUE TITLE
isMonetized is false during monetizationprogress

### ISSUE THREAD

**Issue by dfoderick** [guidovizoso/react-monetize#1]
https://github.com/guidovizoso/react-monetize/blob/082f7c109017c2d95e1476c6fd0cfdf15d87f191/src/MonetizeContext/reducers.ts#L43

Shouldn't it be true during progress?

Trying to use your library and running into a bug.

**Comment by guidovizoso** [comment]
You're right. Good catch!
It's a little late here so I'll fix it tomorrow morning.

Thanks Dave!

**Comment by guidovizoso** [comment]
Fixed in 304a7be6e3bd607f3d844b1892065bc2e55d3112

Thanks for reporting this Dave!
